apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: seeder.cloud.sap
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    url: https://ccloud-seeder.{{ .Values.global.region }}.cloud.sap/mutate_domains/spec.domains
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: mutate-domains.spec.domains.seeder.cloud.sap
  namespaceSelector: {}
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - seeder.cloud.sap
    apiVersions:
    - v1
    operations:
    - '*'
    resources:
    - ccloudseeds
    scope: '*'
  sideEffects: None
  timeoutSeconds: 30