apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # the setup we need to have here is tricky:
  # we need to have a cluster role, in order to be able to access the CRDs of all namespaces
  # on application layer, we only deploy the resources which belong to this environment with "namespace-patterns"
  # for a global-enabled region, we make multiple deployments of the seeder, so we get a clash of the cluster roles
  # therefore, we use the Release-name here as name, so we get cluster roles distinct per deployment
  name: {{ .Release.Name }}
rules:

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [seeder.cloud.sap]
    resources: [clusterkopfpeerings]
    verbs: [list, watch, patch, get]

  # Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]

  # Framework: admission webhook configuration management.
  - apiGroups: [admissionregistration.k8s.io]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: [create, patch]

  # Application: read-only access for watching cluster-wide.
  - apiGroups: [seeder.cloud.sap]
    resources: [ccloudseeds]
    verbs: [list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ccloud-seeder-namespaced
rules:

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [seeder.cloud.sap]
    resources: [kopfpeerings]
    verbs: [list, watch, patch, get]

  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [""]
    resources: [events]
    verbs: [create]

  # Application: watching & handling for the custom resource we declare.
  - apiGroups: [seeder.cloud.sap]
    resources: [ccloudseeds]
    verbs: [list, watch, patch]

  # Application: other resources it produces and manipulates.
  # Here, we create Jobs+PVCs+Pods, but we do not patch/update/delete them ever.
  - apiGroups: [batch, extensions]
    resources: [jobs]
    verbs: [create]
  - apiGroups: [""]
    resources: [pods, persistentvolumeclaims]
    verbs: [create]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: ccloud-seeder
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ccloud-seeder-namespaced
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ccloud-seeder-namespaced
subjects:
  - kind: ServiceAccount
    name: ccloud-seeder
    namespace: {{ .Release.Namespace }}
