apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ccloud-seeder
rules:

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [seeder.cloud.sap]
    resources: [clusterkopfpeerings]
    verbs: [list, watch, patch, get]

  # Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]

  # Framework: admission webhook configuration management.
  - apiGroups: [admissionregistration.k8s.io]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: [create, patch]

  # Application: read-only access for watching cluster-wide.
  - apiGroups: [seeder.cloud.sap]
    resources: [ccloudseeds]
    verbs: [list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: "monsoon3"
  name: ccloud-seeder-namespaced
rules:

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [seeder.cloud.sap]
    resources: [kopfpeerings]
    verbs: [list, watch, patch, get]

  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [""]
    resources: [events]
    verbs: [create]

  # Application: watching & handling for the custom resource we declare.
  - apiGroups: [seeder.cloud.sap]
    resources: [ccloudseeds]
    verbs: [list, watch, patch]

  # Application: other resources it produces and manipulates.
  # Here, we create Jobs+PVCs+Pods, but we do not patch/update/delete them ever.
  - apiGroups: [batch, extensions]
    resources: [jobs]
    verbs: [create]
  - apiGroups: [""]
    resources: [pods, persistentvolumeclaims]
    verbs: [create]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ccloud-seeder-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ccloud-seeder
subjects:
  - kind: ServiceAccount
    name: ccloud-seeder
    namespace: "monsoon3"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: "monsoon3"
  name: ccloud-seeder-namespaced
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ccloud-seeder-namespaced
subjects:
  - kind: ServiceAccount
    name: ccloud-seeder