apiVersion: v1
kind: ConfigMap
metadata:
  name: ccloud-seeder
  namespace: monsoon3
data:
  config.ini: |
    [operator]
    version = 1.0
    handler = domains,groups,projects.projects,role_assignments,projects.networks,projects.subnet_pools,projects.address_scopes,projects.network_quotas
    [crd_names]
    version = v1
    group = seeder.cloud.sap
    kind = CcloudSeed
    plural = ccloudseeds
