apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ccloudseeds.seeder.cloud.sap
spec:
  scope: Namespaced
  group: seeder.cloud.sap
  names:
    kind: CcloudSeed
    plural: ccloudseeds
    singular: ccloudseed
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - name: Duration
          type: string
          priority: 0
          jsonPath: .spec.duration
          description: For how long the seed was running.
        - name: State
          type: string
          priority: 0
          jsonPath: .status.state
          description: As returned from the handler (sometimes).
        - name: LatestError
          type: string
          priority: 0
          jsonPath: .status.latest_error
          description: Error message if the seed failed.
        - name: Changes
          type: string
          priority: 0
          jsonPath: .status.changes
          description: changes being applied.
        - name: LatestReconcile
          type: date
          priority: 0
          jsonPath: .status.latest_reconcile
          description: When the CcloudSeed was last updated.
        - name: Age
          type: date
          priority: 0
          jsonPath: .metadata.creationTimestamp
          description: When the CcloudSeed was created.
