apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
    disco: "true"
    {{- include "utils.linkerd.ingress_annotation" . | indent 4 }}
    {{- if .Values.global.is_global_region }}
    kubernetes.io/ingress.class: "nginx-external"
    {{- end }}
  labels:
    app: ccloud-seeder
  name: ccloud-seeder-webhook
spec:
  {{- if .Values.global.is_global_region }}
  ingressClassName: "nginx-external"
  {{- end }}
  rules:
  - host: {{ .Values.ccloud_seeder.domainPrefix }}.{{ .Values.global.region }}.cloud.sap
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: ccloud-seeder
              port:
                number: 80
  tls:
  - hosts:
    - {{ .Values.ccloud_seeder.domainPrefix }}.{{ .Values.global.region }}.cloud.sap
    secretName: tls-{{ .Values.ccloud_seeder.domainPrefix }}-{{ .Values.global.region }}-cloud-sap
