apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ccloud-seeder
  namespace: monsoon3
data:
  OS_AUTH_URL: {{ required ".Values.keystone.authUrl undefined" .Values.keystone.authUrl | b64enc | quote }}
  OS_USERNAME: {{ required ".Values.keystone.username undefined" .Values.keystone.username | b64enc | quote }}
  OS_PASSWORD: {{ required ".Values.keystone.password undefined" .Values.keystone.password | b64enc | quote }}
  OS_USER_DOMAIN_ID: {{ required ".Values.keystone.userDomainId undefined" .Values.keystone.userDomainId | b64enc | quote }}
  OS_PROJECT_NAME:  {{ required ".Values.keystone.projectName undefined" .Values.keystone.projectName | b64enc | quote }}
  OS_PROJECT_DOMAIN_ID: {{ required ".Values.keystone.projectDomainId undefined" .Values.keystone.projectDomainId | b64enc | quote }}