apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ccloud-seeder
data:
  {{- if .Values.keystone.authUrl }}
  OS_AUTH_URL: {{ .Values.keystone.authUrl | b64enc | quote }}
  {{- else }}
  OS_AUTH_URL: {{ printf "%s/v3" (include "keystone_url" .) | b64enc | quote }}
  {{- end }}
  OS_USERNAME: {{ required ".Values.keystone.username undefined" .Values.keystone.username | b64enc | quote }}
  OS_PASSWORD: {{ required ".Values.keystone.password undefined" .Values.keystone.password | b64enc | quote }}
  OS_USER_DOMAIN_ID: {{ required ".Values.keystone.userDomainId undefined" .Values.keystone.userDomainId | b64enc | quote }}
  OS_PROJECT_NAME:  {{ required ".Values.keystone.projectName undefined" .Values.keystone.projectName | b64enc | quote }}
  OS_PROJECT_DOMAIN_ID: {{ required ".Values.keystone.projectDomainId undefined" .Values.keystone.projectDomainId | b64enc | quote }}
