kind: Service
apiVersion: v1
metadata:
  name: ccloud-seeder
  namespace: monsoon3
  labels:
    type: operator
    service: ccloud-seeder
  annotations:
  {{- include "utils.linkerd.pod_and_service_annotation" . | indent 8 }}
spec:
  selector:
    app: ccloud-seeder
  ports:
    - name: metrics
      port: 9000
    - name: webhook
      port: 80