ccloud_seeder:
  image:
    name: ccloud-seeder
    tag: latest
  domainPrefix: ccloud-seeder

operator:
  dry_run: true
  log_level: INFO
  namespacePatterns: "*"

global:
  linkerd_requested: false

owner-info:
  helm-chart-url: "https://github.com/sapcc/seeder-ccloud/tree/main/charts"
  maintainers:
    - Stefan Hipfel
  support-group: compute-storage-api
  service: seeder
